[project]
name = "rag-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.11.1",
    "fastapi[standard]>=0.135.3",
    "fitz>=0.0.1.dev2",
    "flagembedding>=1.4.0",
    "httpx>=0.28.1",
    "nltk>=3.9.4",
    "ollama>=0.6.1",
    "pymupdf>=1.27.2.2",
    "qdrant-client>=1.17.1",
    "sentence-transformers>=5.4.1",
]
